name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  lint:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint:check

  test-unit:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: yarn install --frozen-lockfile
    - name: Run Unit Test
      run: yarn test:unit
